### ISSUE TITLE
Dubious Customer type

### ISSUE THREAD

**Issue by bitemyapp** [dmjio/stripe#40] opened 2016-04-18 20:38 UTC
https://github.com/dmjio/stripe/blob/master/stripe-core/src/Web/Stripe/Types.hs#L245-L263

Sum of product with exported record fields is a good way to get accidental partial functions. Is there a reason it is implemented in this manner for what should probably be a split out sum type or error condition of the GetCustomer request?

**Comment by dmjio** [comment] 2016-04-18 20:42
yea, this is a known problem, https://github.com/dmjio/stripe/issues/18

**Comment by dmjio** [comment] 2017-03-04 21:03
Closing because duplicate of #18

**Closed by dmjio** 2017-03-04 21:03 UTC
